version: '3.8'
services:
  db:
    image: postgres:15.3-alpine
    restart: always
    container_name: decisioner-db
    environment:
      POSTGRES_DB: decisioner-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
